name: PyCoverage

on: [push]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.0
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.0
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
    - name: Analysing the code with pylint
      run: |
        coverage run -m tests
    - name: Upload coverage to codecov
      uses: codecov/codecov-action@v2
      with:
        files: *.coverage
