name: PyCoverage

on: [push]

jobs:
  coverage:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.0
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.0
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install coverage
    - name: Run coverage
      run: |
        coverage run -m pytest
        cat .coverage
    - name: Upload coverage
      uses: codecov/codecov-action@v2
      with:
        files: .coverage
